# Generated by Django 3.2.6 on 2021-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication_app', '0010_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('post', models.ManyToManyField(related_name='tags', to='publication_app.Post')),
            ],
        ),
    ]
