# Generated by Django 3.2.9 on 2022-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
        ('tag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='comment',
            field=models.ManyToManyField(related_name='tags', to='comments_app.Comment'),
        ),
    ]
