# Generated by Django 3.2.6 on 2021-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0009_alter_post_user'),
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
