# Generated by Django 3.2.9 on 2021-12-20 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
        ('publication_app', '0011_auto_20211215_2101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments_app.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publication_app.post'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post'), ('user', 'comment')},
        ),
    ]
