# Generated by Django 3.2.9 on 2022-01-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_app', '0002_auto_20211220_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-1-12 11:20:53.917285'),
            preserve_default=False,
        ),
    ]
