# Generated by Django 3.2.9 on 2022-01-17 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0002_tag_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tag_app.tag'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='following_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('follower_user', 'following_user'), ('follower_user', 'tag')},
        ),
    ]
