# Generated by Django 3.2.6 on 2021-12-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('publication_app', '0007_auto_20211202_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
