# Generated by Django 3.2.9 on 2022-03-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date', '-id']},
        ),
    ]
