# Generated by Django 3.2.6 on 2021-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_auto_20211208_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images'),
        ),
    ]
